[workspace]
members = ["core", "neurotech", "data_models", "tools"]
resolver = "2"

[workspace.dependencies]
neuroformats = "0.9" # For reading FreeSurfer, MGH/MGZ files[citation:1]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
